" Minimal, dependency-free config for plain vim.
" Neovim is the primary editor (see home/config/nvim); this is just a fallback
" for machines/contexts where only real vim is available.

set nocompatible
filetype plugin indent on
syntax on

set autoread
let mapleader = ','

" ui
set number
set scrolloff=5
set showmatch
set hidden
colorscheme desert

" search
set ignorecase
set smartcase
set incsearch
set nohlsearch

" indentation: 4-space, expand tabs
set shiftwidth=4
set tabstop=4
set expandtab
set autoindent
set smartindent
set smarttab
set textwidth=80

" files: no backups/swap, persistent undo
set nobackup
set nowritebackup
set noswapfile
set undofile
set undodir=~/.vim/undo
if !isdirectory($HOME . '/.vim/undo')
    call mkdir($HOME . '/.vim/undo', 'p')
endif

set backspace=indent,eol,start

" quit insert mode with jk
inoremap jk <Esc>
