#!/bin/sh

ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
brew install bash-completion git macvim mosh wget tmux
echo "Download manually"
echo "-----------------"
echo "Google Drive"
echo "Firefox"
echo "PyCharm"
echo "Spotify"
echo "iTerm"
echo "VLC"
