#!/bin/bash

sudo apt-get update && \
sudo apt-get dist-upgrade && \
sudo apt-get install --no-install-recommends \
xinit gnome-core desktop-base network-manager-gnome \
gnome-color-manager gimp gnome-tweak-tool \
libreoffice-gtk3 gstreamer1.0-plugins-ugly \
rhythmbox rhythmbox-plugins transmission-gtk \
xmonad xmobar libghc-xmonad-contrib-dev gnome-mplayer \
build-essential kupfer scrot stalonetray \
chromium vim vim-gtk unzip alsa-utils \
texlive texlive-latex-extra texlive-fonts-extra latex-beamer \
git exuberant-ctags ssh \
tmux bash-completion
