#!/bin/bash

cd ..

for name in *; do
    target="$HOME/.$name"
        if [[ $name == 'bin' ]]; then
            # Harcoded bin reference
            target="$HOME/$name"
        fi
        if [[ $name != 'README' && $name != 'scripts' ]]; then
            echo "Creating $target"
            if [ -e $target ]; then
                mv "$target" "$target".bk
            fi
            ln -s "$PWD/$name" "$target"
        fi
done

