#!/bin/bash

cd ..

for name in *; do
    target="$HOME/.$name"
    if [[ $name == 'gtk-3.0' || $name == 'nvim' ]]; then
        mkdir -p ~/.config
        target="$HOME/.config/$name"
    fi
    if [[ $name != 'misc' && $name != 'README' && $name != 'scripts' ]]; then
        echo "Creating $target"
        if [ -e $target ]; then
            mv "$target" "$target".bk
        fi
        if [ -h $target ]; then
            rm "$target"
        fi
        ln -s "$PWD/$name" "$target"
    fi
done
